version: "3"
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_DATABASE: springbootapp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3307

  redis:
    image: redis
    ports:
      - 6379:6379

  springbootapp:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mariadb
      - redis